### ISSUE TITLE
README and LICENSE required

### ISSUE THREAD

**Issue by eddieantonio** [naturalness/partycrasher#1]
If we intend on having people use this as a regular old Python package, it should be in `.rst` format. As well, we should have a `setup.py` and `requirements.txt`.

(Also, you should add me as a collaborator on this project.)

**Comment by eddieantonio** [comment]
`requirements.txt` should look something like this:

```
chardet==2.3.0
python-dateutil==2.4.2
six==1.10.0
wheel==0.24.0
```

**Comment by hazelybell** [comment]
Closing this and why wheel?

**Comment by eddieantonio** [comment]
Because wheel just have to try it. :smiley_cat:
