### ISSUE TITLE
Create Integration Testing Environment

### ISSUE THREAD

**Issue by eddieantonio** [naturalness/partycrasher#10]
@orezpraw wants us to depend primarily on integration tests. So our testing infrastructure should:
- [ ] Directly access ElasticSearch
- [ ] Start up a mongrel2 server with our handler
- [ ] Query our handler (using actual HTTP!) with realistic queries

**Comment by abramhindle** [comment]
devenv in bugparty-docker already is capable of running tests.

Take a look there.

**Comment by abramhindle** [comment]
devenv and bugparty use nosetests

**Comment by hazelybell** [comment]
Tests are currently done with plain unittest that comes with Python which is compatible with nose, nose2, py.test, and just running the files. It should stay that way. 

mongrel2 won't be supported. 

written tests using actual http queries are now in the repository in rest_service_tests.py
