### ISSUE TITLE
rest_service_tests.py fails due to missing functionality

### ISSUE THREAD

**Issue by hazelybell** [naturalness/partycrasher#11]

**Comment by eddieantonio** [comment]
cSaid functionality is:
- [x] Fetch a bucket and its reports
- [x] Fetching an individual report
- [x] Query top-buckets for a given timeframe

---
- [x] Add multiple reports
- [x] ~~Dry-run adding a report (report bucket querying)~~ See: #25 
- [x] ~~Remove a report~~ See: #17 

Additionally, the tests must reflect what's in the API docs (errors, additional response headers), as well as features such as `bucket_url`.

**Comment by eddieantonio** [comment]
All essential features pass their tests now.
