### ISSUE TITLE
Document REST API

### ISSUE THREAD

**Issue by hazelybell** [naturalness/partycrasher#13]
Tests should be used as the reference

**Comment by eddieantonio** [comment]
Docs now hosted here: http://partycrasher.readthedocs.org/en/latest/

They're not quite based on the tests yet.

**Comment by eddieantonio** [comment]
@orezpraw: Documentation is written _only_ in each endpoints' docstring; `docs/conf.py` :sparkles: _automagically_ :sparkles:  generates the appropriate ReStructuredText document, which is subsequently rendered by Sphinx, either locally, or on [ReadTheDocs.org](http://rtfd.org).

For style, should we go with the parameterized style I was using for the proposed API, or provide more concrete examples, as in the [GitHub API](https://developer.github.com/v3/issues/#list-issues)?

**Comment by eddieantonio** [comment]
Now the docs just need to be cleaned up, but they're pretty much ready.

**Comment by eddieantonio** [comment]
Apart from adding a few more threshold values for examples, it's pretty much done!
