### ISSUE TITLE
Requires CORS support

### ISSUE THREAD

**Issue by eddieantonio** [naturalness/partycrasher#14]
As it stands, cross-origin requests won't work. Ideally, our tests should attempt to request from a different origin than the PartyCrasher origin.

**Comment by hazelybell** [comment]
is `from flask.ext.cors import CORS; CORS(app)` reliable or broken? We had troubles with it but then I used it yesterday and it worked fine

**Comment by eddieantonio** [comment]
I think "our" previous troubles was just PEBKAC :stuck_out_tongue_winking_eye:

**Comment by eddieantonio** [comment]
Fixed as of a6de1ebeaa63dc6522cec4ee9c855c56ae0c82b5

I've updated all relevant tests (most of them).
