### ISSUE TITLE
URL threshold parameter resets when opening bucket and report.

### ISSUE THREAD

**Issue by Skroman** [naturalness/partycrasher#149]
When the threshold parameter is modified on the /ui to something other than 3.8 and a user clicks a bucket, the bucket does not load properly.
e.g. scenario:
- update the bucket threshold to something other than 3.8
> http://localhost:5000/ui/thresholds/5.1/buckets/?size=10&from=10
- then click a bucket!
> http://localhost:5000/ui/thresholds/5.1/buckets/ahsOeT8Z2DwrykV7/reports/
- but during the load the URL updates auto-magically :(
> http://localhost:5000/ui/thresholds/3.8/buckets/ahsOeT8Z2DwrykV7/reports/

Work around: press the browser back button and it will show the loaded non-3.8 threshold bucket.

This scenario is repeated when attempting to load a crash report from a non-3.8 bucket:
- click a report from a bucket
> http://localhost:5000/ui/thresholds/5.1/buckets/ahsOeT8Z2DwrykV7/reports/veryUniqueSecretDBKey-1
- then it starts to load
> http://localhost:5000/ui/thresholds/3.8/buckets/ahsOeT8Z2DwrykV7/reports/veryUniqueSecretDBKey-1/
- it loaded but then went to the 3.8 threshold page, so click the browser back button
> http://localhost:5000/ui/thresholds/5.1/buckets/ahsOeT8Z2DwrykV7/reports/veryUniqueSecretDBKey-1/
- it loads as expected.

**Comment by hazelybell** [comment]
Can't reproduce. Can you show me this happening tomorrow?

**Comment by hazelybell** [comment]
Nevermind. I see what you mean.
