### ISSUE TITLE
Consider using Silk as a test runner

### ISSUE THREAD

**Issue by eddieantonio** [naturalness/partycrasher#16]
[Silk](https://github.com/matryer/silk) allows one to author Markdown documents describing API endpoints and runs the Markdown as a test. [We have already written documentation like this before](https://github.com/orezpraw/partycrasher/issues/3).

**Comment by abramhindle** [comment]
That project started this year. ipython https://ipython.org/  can do the same thing and is far more robust -- it's just maintained, huge, and aimed at science. For example https://github.com/google/deepdream/blob/master/dream.ipynb

I think silk is too new. Furthermore it requires us to rely on go as well.

**Comment by eddieantonio** [comment]
ipython/Jupyter is pretty rad, but it doesn't test a spec the same way Silk does. Markdown+code isn't the end of the story; the Markdown _is_ the test. That said, you're right; we'd be early adopters, so maybe create boring old unit tests using `requests`.
