### ISSUE TITLE
Assign reports to projects based on ES types?

### ISSUE THREAD

**Issue by eddieantonio** [naturalness/partycrasher#20]
Should we use ElasticSearch types within the crashes index to categorize crash reports by project?

**Comment by abramhindle** [comment]
Please clarify what you meant ElasticSearch types? 

Like add the "_project" field to the schema for that index?

**Comment by eddieantonio** [comment]
Maybe I'm not understanding this feature properly, but [types](https://www.elastic.co/guide/en/elasticsearch/reference/current/_basic_concepts.html#_type)

So that we can get all buckets for a project like this:

``` sh
curl -XGET localhost:9200/crashes/alan_parsons/_search # query stuff here
```

**Comment by abramhindle** [comment]
That might be a cheaper way of dealing with it. You can set project to _type in the main object and you'd be none-the-wiser.
