### ISSUE TITLE
Handle ElasticSearch 1/2 differences in MoreLikeThis query

### ISSUE THREAD

**Issue by eddieantonio** [naturalness/partycrasher#26]
In ElasticSearch 1.x, this is how you search for an [artificial document](https://www.elastic.co/guide/en/elasticsearch/reference/1.7/query-dsl-mlt-query.html#query-dsl-mlt-query):

```
{
    "query": {
        "more_like_this": {
            "min_doc_freq": 0,
            "docs": [
                {
                    "doc": {
                        "project": "alan_parsons",
                        "database_id": "116a4f69-4d54-4f6e-997b-e2cf3f88a5e9"
                    },
                    "_type": "crash",
                    "_index": "crashes"
                }
            ],
            "max_query_terms": 2500,
            "min_term_freq": 0
        }
    }
}
```

However, in [ElasticSearch 2.x](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-mlt-query.html#query-dsl-mlt-query):

```
{
    "more_like_this" : {
        "fields" : ["name.first", "name.last"],
        "like" : [
        {
            "_index" : "marvel",
            "_type" : "quotes",
            "doc" : {
                "name": {
                    "first": "Ben",
                    "last": "Grimm"
                },
                "tweet": "You got no idea what I'd... what I'd give to be invisible."
              }
            }
        },
        {
            "_index" : "marvel",
            "_type" : "quotes",
            "_id" : "2"
        }
        ],
        "min_term_freq" : 1,
        "max_query_terms" : 12
    }
}
```

**Comment by abramhindle** [comment]
How many places do you need to parse MLT? If it's 1 place, this is a 2 method 1 if statement kind of problem.

**Comment by eddieantonio** [comment]
You're right, however, we still have to specify the version of ElasticSearch used in the config. It requires a bit of effort, and right now I'm just targeting 1.x.

**Comment by abramhindle** [comment]
No you don't need to do that. 1 conditional in python isn't going to hurt you, you're already using python.

``` python
if 'query' in response_json:
   return self.parse_es1_mlt(response_json)
else:
   return self.parse_es2_mlt(response_json)
```

**Comment by eddieantonio** [comment]
Ah! No, I'm not _parsing_ the query; I'm building it. And the `"query"` field is optional, as far as I understand, so it doesn't differentiate anything. What does differentiate 1.x and 2.x is `"like"` vs. `"docs"` in the `"more_like_this"` query.

**Comment by eddieantonio** [comment]
Currently non-replicable?
