### ISSUE TITLE
Create daily indices

### ISSUE THREAD

**Issue by eddieantonio** [naturalness/partycrasher#39]
And search based on index patterns.

**Comment by abramhindle** [comment]
This sounds like a heck of refactoring and a complication, but there's a good chance we need to do it.

Now what I really want to see is an abstraction for this kind of storage. I want you to write your elasticsearch query and submit it and then have that query rewritten to handle the multiple indices. So consider an API where you submit a query fragment that will be used to composed the larger query.

e.g.

```
es_api.query("project",timeStart,timeEnd,"{ ... query ...}")
```

becomes

```
GET /project2016-01-01,project2016-01-02,2016-01-03/_search
     { ... query ... }
```

Etc. Make it easy.

Resource used: https://www.elastic.co/guide/en/elasticsearch/guide/current/multi-index-multi-type.html

**Comment by abramhindle** [comment]
Story: As project owner, I want to know the difference in performance between these methods.
Story: as a db admin, for DB performance, I want "time-based sharding"
Story: as a db admin, when I delete a project all of its indices should be deleted as well. project*

Concern: If the date range is too funny will the GET URI be too big?

**Comment by eddieantonio** [comment]
The reason we suggested this is because Michelle told us that ElasticSearch
has builtin support for this complication.

https://www.elastic.co/guide/en/elasticsearch/guide/current/index-templates.html

Basically, instead of defining an index as we are now, we define a template
and just insert as usual. Then the queries are simply patterns for the
given date---not actually a query or parameter for each individual day.
It's how logstash works.

**Comment by eddieantonio** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/current/multi-index.html

**Comment by eddieantonio** [comment]
Unnecessary at this point. We'll leave this as a future scalability concern.
