### ISSUE TITLE
Missing configuration system

### ISSUE THREAD

**Issue by hazelybell** [naturalness/partycrasher#4]

**Comment by eddieantonio** [comment]
For our initial version, we might as well just put a bunch of things in a `.cfg`/`.ini` file instead of having it dynamically modifiable. Then just parse it on start-up using [`configparser`](https://docs.python.org/3/library/configparser.html) For example:

``` ini
[buckets]
thresholds = 3.5,3.8,3.9,4.0,4.1,4.2,4.5
default = 4.0

[index]
stack-frames = true
context = true
tokenization = camel

[elastic]
primary = localhost
```

**Comment by abramhindle** [comment]
Guys please look at bug-party. It already deals with configs and ini files.

**Comment by eddieantonio** [comment]
We also need to configure the path prefix.

**Comment by hazelybell** [comment]
There is no path prefix, docs updated to reflect that.

**Comment by abramhindle** [comment]
We'll need a path prefix. If we're to do HATEOAS we need it and if we use proxying with it we need to get it to rewrite its own paths in the JSON output. You cannot ask a proxy server/proxy frontend to do this. Just like how you have to know what your end-point hostname and port will be regardless of what flask binds to.
