### ISSUE TITLE
Demoable user interface

### ISSUE THREAD

**Issue by abramhindle** [naturalness/partycrasher#40]
We need a demoable user interface.

The goal is to demonstrate how clients can integrate this information in their own systems.

The user interface should use the same API that we expect clients to use.

The user interface should be heavy client side.

Technology stack: angular 1.\* stable and bootstrap (if you want)

User interface stories:
- [x] As a user, I want to see the latest buckets
- [x] As a user, I want to view a single crash report
- [x] As a user, I want to change bucketing threshold to see similar reports
- [ ] As a user, I want to ORDER buckets (I like big buckets, I cannot lie)
- [x] As a user, I want to see crash reports related to a single report (buckets?)
- [x] As a user, I want to browse buckets
- [x] As a user, I want to browse buckets by project.
- [ ] As a user, I want to browse crashes
  - [x] As a user, I want to search for crashes by items in the stack trace
- [ ] As a user, I want to query for similar crash reports
- [x] As a user, I want to browse crashes by project
- [x] As a user, I want to see the latest crashes
- [ ] As a user, I want to see statistics about buckets and crashes
  - [ ] how many buckets
  - [ ] distribution of crashes per bucket
- [x] As a project owner, I want more user stories that I forget :(

Cool stuff:
- As project owner, I want it to be cool enough that YOU (Eddie/Josh) can demo it at demo-camp
- A cool streamgraph of buckets like Joshua's slide but in streamgraph style.

**Comment by eddieantonio** [comment]
Cool stuff point 1 is ambiguous. I interpret it as adding visual flare such as the following animated graphics interchange format images:

![](http://i.giphy.com/adSYb2uHlyoCc.gif)
![](http://i.giphy.com/lz25eb00stUAg.gif)
![](http://i.giphy.com/awbbYFIqgcQSY.gif)

This is what you wanted, right?

**Comment by eddieantonio** [comment]
@abramhindle can you elaborate on "I want to browse crashes". This point is unclear to me.

**Comment by eddieantonio** [comment]
~~(somewhat) Blocked on #42~~

Lolno

**Comment by eddieantonio** [comment]
@naturalness/owners 
This is what I whipped up so far. It's lacking in several ways, but please offer me your critique. 

### Top Crashes

![top-crashes](https://cloud.githubusercontent.com/assets/2294397/15413544/9c98cce6-1dee-11e6-8c83-41f461c6a679.png)

### Bucket view

![bucket](https://cloud.githubusercontent.com/assets/2294397/15413545/9c9bdf8a-1dee-11e6-8d9a-ac8768d4b4d7.png)

**Comment by abramhindle** [comment]
I can't say much until I see what a trace in a bucket looks like. I think we should have the meta data but the stack trace is of interest. If it could be shown first or at the top that'd be great.

Maybe top lines of the traces or something. The context you show is quite detailed but not necessarily what is important when a human looks at a crash report.

Maybe use 2 columns?
