### ISSUE TITLE
A way to name buckets?

### ISSUE THREAD

**Issue by eddieantonio** [naturalness/partycrasher#48]
We may need to auto-generate a name for buckets, or allow developers to name buckets themselves. Although the bucket IDs suffice for differentiating buckets, they are not so useful for human identification.

**Comment by abramhindle** [comment]
Well you could go GUID and not worry about it. We could also use projectname+hash . It could be projectname plus random 64bit long -- no hashing. We could also make a dictionary of pleasant words ala docker.

**Comment by eddieantonio** [comment]
> Well you could go GUID and not worry about it.

This is the current solution. My issue is that a person isn't going to easily remember and recognize a GUID.

> We could also make a dictionary of pleasant words ala docker.

I like this suggestion best. I'll mark this issue as low-priority, however.

**Comment by eddieantonio** [comment]
Build signature would be REALLY nice, but this would be a bad idea on first ingest.

**Comment by eddieantonio** [comment]
More or less resolved by keywords feature.
