### ISSUE TITLE
Take project name into consideration when creating internal IDs

### ISSUE THREAD

**Issue by eddieantonio** [naturalness/partycrasher#49]
If two projects use the same manner of generating IDs and they both post reports to PartyCrasher, then report IDs may collide. So the reports from the project that got there first will be ingested, and the reports from the other project will be rejected. Instead, when considering if two reports are truly different, consider both the project AND the `database_id` as part of the internal ID.
- [x] Concatenate `project` and `database_id` when constructing internal IDs
- [x] Ensure that routes that inject crashes take these two factors into account.

**Comment by abramhindle** [comment]
I agree with this. Keep database_id small and maybe random. like 2-4 chars.

**Comment by eddieantonio** [comment]
Right now, we make the outside party chose the report IDs. That's why Josh named them "database" IDs — they come from an external database. Incidentally, this is how we "check" for identical reports. "Identical" as in, "this is the same report in the universe, you just gave it to me twice." Not identical as in "Wow, these two distinct reports look exactly the same!"
