### ISSUE TITLE
Ensure the back button works in the browser on all pages

### ISSUE THREAD

**Issue by ghost** [naturalness/partycrasher#73]

**Comment by eddieantonio** [comment]
Can you list the pages that the back is button is broken on?

**Comment by ghost** [comment]
It happens whenever it changes the URL on the first page load like if you go to just /ui/

**Comment by eddieantonio** [comment]
That's probably due to [the redirect](https://github.com/naturalness/partycrasher/blob/cf6a19b49a3d50dd4676c4915268054e6711da42/partycrasher/ngapp/app/scripts/app.js#L19-L22):

``` javascript
    $routeProvider
      .when('/', {
        /* Redirect to top buckets for ALL projects. */
        redirectTo: `/*/buckets/${DEFAULT_THRESHOLD}`
      })
```

**Comment by ghost** [comment]
Yeah, so I guess the solution is to only call that when something actually gets clicked not on initial page load regardless if the url isn't great...
