### ISSUE TITLE
Make Mongrel2 RESTful Handler (BugParty-Compatible)

### ISSUE THREAD

**Issue by eddieantonio** [naturalness/partycrasher#8]
We can still keep things separate for now, but with the eventual plans of integrating it into BugParty (it should be able to run on the same server--Mongrel2).

The RESTful service should be served from Mongrel2Handler, probably from the root path `/partycrasher/`.

TODOS
- [ ] `mongrel.conf`
- [ ] Mongrel2Handler
- [ ] Ensure proper caching (Etags)

Suggestion:
- Copy Alex's excellent Mongrel code from BugParty

As dictated from the PI.

**Comment by abramhindle** [comment]
I would clone and strip mongrel2.conf and the first handler + abstractions for handlers from bugparty and remerge it later.

What I want is to take advantage of mongrel2's ability to have multiple handlers handle the same path so we choose how many crashparty workers we want, and they are distinct handlers from the somewhat monolithic bugparty handler.

This ensures good concurrent request handling while still maintaining the one mongrel2 webservice.

**Comment by eddieantonio** [comment]
Is Mongrel2 for Python deprecated?

``` sh
$ pip install mongrel2
  Could not find a version that satisfies the requirement mongrel2 (from versions: )
No matching distribution found for mongrel2
```

And the package URL mentioned in the [Mongrel2's official examples](https://github.com/mongrel2/mongrel2/blob/master/examples/python/setup.py) is a 404 as well...

**Comment by abramhindle** [comment]
Checkout the dockerfile here https://bitbucket.org/abram/bugparty-docker/src/85f0d2516c37c72dd1113b887c6b0fe6798802b3/mongrel2/Dockerfile?at=master&fileviewer=file-view-default

```
# setup mongrel2
RUN git clone https://github.com/zedshaw/mongrel2.git
RUN cd ~ && cd mongrel2 && make all install && \
    cd examples/python && python setup.py install
```

Install the python module FROM mongrel2 itself. Mongrel2 is still up to date (maintenance seen a month ago).

**Comment by hazelybell** [comment]
WONTFIX
